PROBLEM := MaximumProfit

prepare:
	mkdir ${PROBLEM}
	sed -e s/MaximumProfit/${PROBLEM}/g Makefile.template > ${PROBLEM}/Makefile
	mkdir ${PROBLEM}/out
	touch ${PROBLEM}/${PROBLEM}.cpp
	mkdir -p ${PROBLEM}/test/case1
